# Generated by Django 3.2.18 on 2023-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('priority_code', models.IntegerField(default=0)),
                ('for_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('for_date', 'title')},
            },
        ),
    ]
