# Generated by Django 3.2.18 on 2023-04-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todo_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('for_date', 'title', 'priority_code')},
        ),
    ]
